export const VERTEX_SHADER_SOURCE = [
  "precision highp float;",
  "",
  "attribute vec2 aPosition;",
  "attribute vec2 aUv;",
  "",
  "uniform mat4 uProjection;",
  "uniform vec2 uTileOffset;",
  "uniform vec2 uTileScale;",
  "uniform float uWaveCenterX;",
  "uniform float uWaveStrength;",
  "uniform float uWaveWidth;",
  "uniform float uWaveIntensity;",
  "uniform float uHoverReveal;",
  "",
  "varying vec2 vUv;",
  "varying float vReveal;",
  "",
  "float quadraticEase(float t) {",
  "  return t < 0.5 ? 2.0 * t * t : 1.0 - pow(-2.0 * t + 2.0, 2.0) * 0.5;",
  "}",
  "",
  "void main() {",
  "  vec2 worldPosition = aPosition * uTileScale + uTileOffset;",
  "  float distanceFromWave = abs(uTileOffset.x - uWaveCenterX);",
  "  float normalizedDistance = clamp(distanceFromWave / uWaveWidth, 0.0, 1.0);",
  "  float falloff = 1.0 - quadraticEase(normalizedDistance);",
  "  float zDeformation = falloff * uWaveStrength;",
  "  gl_Position = uProjection * vec4(worldPosition, zDeformation, 1.0);",
  "  vUv = aUv;",
  "  vReveal = clamp(max(falloff * uWaveIntensity, uHoverReveal), 0.0, 1.0);",
  "}"
].join("\n");

export const FRAGMENT_SHADER_SOURCE = [
  "precision highp float;",
  "",
  "varying vec2 vUv;",
  "varying float vReveal;",
  "",
  "uniform sampler2D uImage;",
  "uniform vec2 uImageAspectCorrection;",
  "uniform vec3 uColorPaper;",
  "uniform vec3 uActiveAccent;",
  "uniform float uHighlight;",
  "uniform float uExplosion;",
  "uniform float uAlpha;",
  "uniform float uParallaxOffset;",
  "",
  "void main() {",
  "  vec2 correctedUv = (vUv - 0.5) * uImageAspectCorrection + 0.5;",
  "  correctedUv.x += uParallaxOffset;",
  "  correctedUv = clamp(correctedUv, 0.0, 1.0);",
  "  vec4 sourceColor = texture2D(uImage, correctedUv);",
  "  float luminance = dot(sourceColor.rgb, vec3(0.299, 0.587, 0.114));",
  "  vec3 desaturated = mix(vec3(luminance), uColorPaper, 0.12);",
  "  vec3 revealedColor = mix(desaturated, sourceColor.rgb, vReveal);",
  "  vec3 withOverprint = mix(revealedColor, uActiveAccent, vReveal * vReveal * 0.16);",
  "  vec3 withExplosion = mix(withOverprint, uActiveAccent, uExplosion);",
  "  vec3 finalColor = withExplosion + uHighlight * 0.05;",
  "  gl_FragColor = vec4(finalColor, sourceColor.a * uAlpha);",
  "}"
].join("\n");
