export const VERTEX_SHADER_SOURCE = [
  "precision highp float;",
  "",
  "attribute vec2 aPosition;",
  "attribute vec2 aUv;",
  "",
  "uniform mat4 uProjection;",
  "uniform vec2 uTileOffset;",
  "uniform vec2 uTileScale;",
  "uniform float uWaveIntensity;",
  "uniform float uHoverReveal;",
  "",
  "varying vec2 vUv;",
  "varying float vReveal;",
  "",
  "void main() {",
  "  vec2 worldPosition = aPosition * uTileScale + uTileOffset;",
  "  gl_Position = uProjection * vec4(worldPosition, 0.0, 1.0);",
  "  vUv = vec2(aUv.x, 1.0 - aUv.y);",
  "  vReveal = clamp(uWaveIntensity, 0.0, 1.0);",
  "}"
].join("\n");

export const FRAGMENT_SHADER_SOURCE = [
  "precision highp float;",
  "",
  "varying vec2 vUv;",
  "varying float vReveal;",
  "",
  "uniform sampler2D uImage;",
  "uniform vec2 uImageAspectCorrection;",
  "uniform vec3 uColorPaper;",
  "uniform vec3 uActiveAccent;",
  "uniform float uHighlight;",
  "uniform float uExplosion;",
  "uniform float uAlpha;",
  "uniform float uParallaxOffset;",
  "uniform float uWaveIntensity;",
  "uniform float uHoverReveal;",
  "",
  "void main() {",
  "  float crop = mix(0.65, 1.0, uExplosion);",
  "  vec2 correctedUv = (vUv - 0.5) * uImageAspectCorrection * crop + 0.5;",
  "  correctedUv = clamp(correctedUv, 0.0, 1.0);",
  "  vec4 sourceColor = texture2D(uImage, correctedUv);",
  "  float luminance = dot(sourceColor.rgb, vec3(0.299, 0.587, 0.114));",
  "  vec3 desaturated = mix(vec3(luminance), uColorPaper, 0.12);",
  "  vec3 finalColor = mix(desaturated, sourceColor.rgb, max(vReveal, uHoverReveal));",
  "  gl_FragColor = vec4(finalColor, sourceColor.a * uAlpha);",
  "}"
].join("\n");
